### ISSUE TITLE
非编译器命令支持

### ISSUE THREAD

**Issue by LiuTianyouOnLuogu** [LiuTianyouOnLuogu/lty-make#1]
我们需要像makefile一样支持非编译器指令的执行。
这在技术上比较难，为了快捷，我不想引入目标的概念。

**Comment by LiuTianyouOnLuogu** [comment]
不用了

**Comment by AMIRIOX** [comment]
这并不难  只需要遍历`$*`然后捕捉`-s=`开头并以`|`分割的字符串, 然后检查这些选项
